name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Copy environment file
        run: cp .env.example .env

      - name: Set environment variables
        run: |
          echo "WWWGROUP=$(id -g)" >> $GITHUB_ENV
          echo "WWWUSER=$(id -u)" >> $GITHUB_ENV
          echo "MYSQL_EXTRA_OPTIONS=" >> $GITHUB_ENV

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@3846bcd61da338e9eaaf83e7ed0234a12b099b72 # v2.4.1
        with:
          compose-file: "./compose.yaml"

      - name: Install Composer dependencies
        run: docker compose exec composer install --prefer-dist --no-interaction --no-progress

      - name: Generate app key
        run: docker compose exec php artisan key:generate

      - name: Execute tests
        run: docker compose exec php artisan test
